"""create all tables

Revision ID: bb964d18f178
Revises: 
Create Date: 2024-03-13 08:52:25.596598

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb964d18f178"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("bet_amount", sa.DECIMAL(scale=2), nullable=False),
        sa.Column("status", sa.String(), server_default="Not played", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bets_event_id"), "bets", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bets_event_id"), table_name="bets")
    op.drop_table("bets")
    # ### end Alembic commands ###
